// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grSim_Commands.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_grSim_5fCommands_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_grSim_5fCommands_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3009000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3009001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_grSim_5fCommands_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_grSim_5fCommands_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_grSim_5fCommands_2eproto;
class grSim_Commands;
class grSim_CommandsDefaultTypeInternal;
extern grSim_CommandsDefaultTypeInternal _grSim_Commands_default_instance_;
class grSim_Robot_Command;
class grSim_Robot_CommandDefaultTypeInternal;
extern grSim_Robot_CommandDefaultTypeInternal _grSim_Robot_Command_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::grSim_Commands* Arena::CreateMaybeMessage<::grSim_Commands>(Arena*);
template<> ::grSim_Robot_Command* Arena::CreateMaybeMessage<::grSim_Robot_Command>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class grSim_Robot_Command :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:grSim_Robot_Command) */ {
 public:
  grSim_Robot_Command();
  virtual ~grSim_Robot_Command();

  grSim_Robot_Command(const grSim_Robot_Command& from);
  grSim_Robot_Command(grSim_Robot_Command&& from) noexcept
    : grSim_Robot_Command() {
    *this = ::std::move(from);
  }

  inline grSim_Robot_Command& operator=(const grSim_Robot_Command& from) {
    CopyFrom(from);
    return *this;
  }
  inline grSim_Robot_Command& operator=(grSim_Robot_Command&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const grSim_Robot_Command& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const grSim_Robot_Command* internal_default_instance() {
    return reinterpret_cast<const grSim_Robot_Command*>(
               &_grSim_Robot_Command_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(grSim_Robot_Command& a, grSim_Robot_Command& b) {
    a.Swap(&b);
  }
  inline void Swap(grSim_Robot_Command* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline grSim_Robot_Command* New() const final {
    return CreateMaybeMessage<grSim_Robot_Command>(nullptr);
  }

  grSim_Robot_Command* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<grSim_Robot_Command>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const grSim_Robot_Command& from);
  void MergeFrom(const grSim_Robot_Command& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(grSim_Robot_Command* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "grSim_Robot_Command";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_grSim_5fCommands_2eproto);
    return ::descriptor_table_grSim_5fCommands_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIdFieldNumber = 1,
    kKickspeedxFieldNumber = 2,
    kKickspeedzFieldNumber = 3,
    kVeltangentFieldNumber = 4,
    kVelnormalFieldNumber = 5,
    kVelangularFieldNumber = 6,
    kSpinnerFieldNumber = 7,
    kWheelsspeedFieldNumber = 8,
    kWheel1FieldNumber = 9,
    kWheel2FieldNumber = 10,
    kWheel3FieldNumber = 11,
    kWheel4FieldNumber = 12,
  };
  // required uint32 id = 1;
  bool has_id() const;
  void clear_id();
  ::PROTOBUF_NAMESPACE_ID::uint32 id() const;
  void set_id(::PROTOBUF_NAMESPACE_ID::uint32 value);

  // required float kickspeedx = 2;
  bool has_kickspeedx() const;
  void clear_kickspeedx();
  float kickspeedx() const;
  void set_kickspeedx(float value);

  // required float kickspeedz = 3;
  bool has_kickspeedz() const;
  void clear_kickspeedz();
  float kickspeedz() const;
  void set_kickspeedz(float value);

  // required float veltangent = 4;
  bool has_veltangent() const;
  void clear_veltangent();
  float veltangent() const;
  void set_veltangent(float value);

  // required float velnormal = 5;
  bool has_velnormal() const;
  void clear_velnormal();
  float velnormal() const;
  void set_velnormal(float value);

  // required float velangular = 6;
  bool has_velangular() const;
  void clear_velangular();
  float velangular() const;
  void set_velangular(float value);

  // required bool spinner = 7;
  bool has_spinner() const;
  void clear_spinner();
  bool spinner() const;
  void set_spinner(bool value);

  // required bool wheelsspeed = 8;
  bool has_wheelsspeed() const;
  void clear_wheelsspeed();
  bool wheelsspeed() const;
  void set_wheelsspeed(bool value);

  // optional float wheel1 = 9;
  bool has_wheel1() const;
  void clear_wheel1();
  float wheel1() const;
  void set_wheel1(float value);

  // optional float wheel2 = 10;
  bool has_wheel2() const;
  void clear_wheel2();
  float wheel2() const;
  void set_wheel2(float value);

  // optional float wheel3 = 11;
  bool has_wheel3() const;
  void clear_wheel3();
  float wheel3() const;
  void set_wheel3(float value);

  // optional float wheel4 = 12;
  bool has_wheel4() const;
  void clear_wheel4();
  float wheel4() const;
  void set_wheel4(float value);

  // @@protoc_insertion_point(class_scope:grSim_Robot_Command)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::uint32 id_;
  float kickspeedx_;
  float kickspeedz_;
  float veltangent_;
  float velnormal_;
  float velangular_;
  bool spinner_;
  bool wheelsspeed_;
  float wheel1_;
  float wheel2_;
  float wheel3_;
  float wheel4_;
  friend struct ::TableStruct_grSim_5fCommands_2eproto;
};
// -------------------------------------------------------------------

class grSim_Commands :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:grSim_Commands) */ {
 public:
  grSim_Commands();
  virtual ~grSim_Commands();

  grSim_Commands(const grSim_Commands& from);
  grSim_Commands(grSim_Commands&& from) noexcept
    : grSim_Commands() {
    *this = ::std::move(from);
  }

  inline grSim_Commands& operator=(const grSim_Commands& from) {
    CopyFrom(from);
    return *this;
  }
  inline grSim_Commands& operator=(grSim_Commands&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const grSim_Commands& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const grSim_Commands* internal_default_instance() {
    return reinterpret_cast<const grSim_Commands*>(
               &_grSim_Commands_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(grSim_Commands& a, grSim_Commands& b) {
    a.Swap(&b);
  }
  inline void Swap(grSim_Commands* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline grSim_Commands* New() const final {
    return CreateMaybeMessage<grSim_Commands>(nullptr);
  }

  grSim_Commands* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<grSim_Commands>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const grSim_Commands& from);
  void MergeFrom(const grSim_Commands& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(grSim_Commands* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "grSim_Commands";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_grSim_5fCommands_2eproto);
    return ::descriptor_table_grSim_5fCommands_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRobotCommandsFieldNumber = 3,
    kTimestampFieldNumber = 1,
    kIsteamyellowFieldNumber = 2,
  };
  // repeated .grSim_Robot_Command robot_commands = 3;
  int robot_commands_size() const;
  void clear_robot_commands();
  ::grSim_Robot_Command* mutable_robot_commands(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::grSim_Robot_Command >*
      mutable_robot_commands();
  const ::grSim_Robot_Command& robot_commands(int index) const;
  ::grSim_Robot_Command* add_robot_commands();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::grSim_Robot_Command >&
      robot_commands() const;

  // required double timestamp = 1;
  bool has_timestamp() const;
  void clear_timestamp();
  double timestamp() const;
  void set_timestamp(double value);

  // required bool isteamyellow = 2;
  bool has_isteamyellow() const;
  void clear_isteamyellow();
  bool isteamyellow() const;
  void set_isteamyellow(bool value);

  // @@protoc_insertion_point(class_scope:grSim_Commands)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::grSim_Robot_Command > robot_commands_;
  double timestamp_;
  bool isteamyellow_;
  friend struct ::TableStruct_grSim_5fCommands_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// grSim_Robot_Command

// required uint32 id = 1;
inline bool grSim_Robot_Command::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void grSim_Robot_Command::clear_id() {
  id_ = 0u;
  _has_bits_[0] &= ~0x00000001u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 grSim_Robot_Command::id() const {
  // @@protoc_insertion_point(field_get:grSim_Robot_Command.id)
  return id_;
}
inline void grSim_Robot_Command::set_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000001u;
  id_ = value;
  // @@protoc_insertion_point(field_set:grSim_Robot_Command.id)
}

// required float kickspeedx = 2;
inline bool grSim_Robot_Command::has_kickspeedx() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void grSim_Robot_Command::clear_kickspeedx() {
  kickspeedx_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline float grSim_Robot_Command::kickspeedx() const {
  // @@protoc_insertion_point(field_get:grSim_Robot_Command.kickspeedx)
  return kickspeedx_;
}
inline void grSim_Robot_Command::set_kickspeedx(float value) {
  _has_bits_[0] |= 0x00000002u;
  kickspeedx_ = value;
  // @@protoc_insertion_point(field_set:grSim_Robot_Command.kickspeedx)
}

// required float kickspeedz = 3;
inline bool grSim_Robot_Command::has_kickspeedz() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void grSim_Robot_Command::clear_kickspeedz() {
  kickspeedz_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline float grSim_Robot_Command::kickspeedz() const {
  // @@protoc_insertion_point(field_get:grSim_Robot_Command.kickspeedz)
  return kickspeedz_;
}
inline void grSim_Robot_Command::set_kickspeedz(float value) {
  _has_bits_[0] |= 0x00000004u;
  kickspeedz_ = value;
  // @@protoc_insertion_point(field_set:grSim_Robot_Command.kickspeedz)
}

// required float veltangent = 4;
inline bool grSim_Robot_Command::has_veltangent() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void grSim_Robot_Command::clear_veltangent() {
  veltangent_ = 0;
  _has_bits_[0] &= ~0x00000008u;
}
inline float grSim_Robot_Command::veltangent() const {
  // @@protoc_insertion_point(field_get:grSim_Robot_Command.veltangent)
  return veltangent_;
}
inline void grSim_Robot_Command::set_veltangent(float value) {
  _has_bits_[0] |= 0x00000008u;
  veltangent_ = value;
  // @@protoc_insertion_point(field_set:grSim_Robot_Command.veltangent)
}

// required float velnormal = 5;
inline bool grSim_Robot_Command::has_velnormal() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void grSim_Robot_Command::clear_velnormal() {
  velnormal_ = 0;
  _has_bits_[0] &= ~0x00000010u;
}
inline float grSim_Robot_Command::velnormal() const {
  // @@protoc_insertion_point(field_get:grSim_Robot_Command.velnormal)
  return velnormal_;
}
inline void grSim_Robot_Command::set_velnormal(float value) {
  _has_bits_[0] |= 0x00000010u;
  velnormal_ = value;
  // @@protoc_insertion_point(field_set:grSim_Robot_Command.velnormal)
}

// required float velangular = 6;
inline bool grSim_Robot_Command::has_velangular() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void grSim_Robot_Command::clear_velangular() {
  velangular_ = 0;
  _has_bits_[0] &= ~0x00000020u;
}
inline float grSim_Robot_Command::velangular() const {
  // @@protoc_insertion_point(field_get:grSim_Robot_Command.velangular)
  return velangular_;
}
inline void grSim_Robot_Command::set_velangular(float value) {
  _has_bits_[0] |= 0x00000020u;
  velangular_ = value;
  // @@protoc_insertion_point(field_set:grSim_Robot_Command.velangular)
}

// required bool spinner = 7;
inline bool grSim_Robot_Command::has_spinner() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void grSim_Robot_Command::clear_spinner() {
  spinner_ = false;
  _has_bits_[0] &= ~0x00000040u;
}
inline bool grSim_Robot_Command::spinner() const {
  // @@protoc_insertion_point(field_get:grSim_Robot_Command.spinner)
  return spinner_;
}
inline void grSim_Robot_Command::set_spinner(bool value) {
  _has_bits_[0] |= 0x00000040u;
  spinner_ = value;
  // @@protoc_insertion_point(field_set:grSim_Robot_Command.spinner)
}

// required bool wheelsspeed = 8;
inline bool grSim_Robot_Command::has_wheelsspeed() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void grSim_Robot_Command::clear_wheelsspeed() {
  wheelsspeed_ = false;
  _has_bits_[0] &= ~0x00000080u;
}
inline bool grSim_Robot_Command::wheelsspeed() const {
  // @@protoc_insertion_point(field_get:grSim_Robot_Command.wheelsspeed)
  return wheelsspeed_;
}
inline void grSim_Robot_Command::set_wheelsspeed(bool value) {
  _has_bits_[0] |= 0x00000080u;
  wheelsspeed_ = value;
  // @@protoc_insertion_point(field_set:grSim_Robot_Command.wheelsspeed)
}

// optional float wheel1 = 9;
inline bool grSim_Robot_Command::has_wheel1() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void grSim_Robot_Command::clear_wheel1() {
  wheel1_ = 0;
  _has_bits_[0] &= ~0x00000100u;
}
inline float grSim_Robot_Command::wheel1() const {
  // @@protoc_insertion_point(field_get:grSim_Robot_Command.wheel1)
  return wheel1_;
}
inline void grSim_Robot_Command::set_wheel1(float value) {
  _has_bits_[0] |= 0x00000100u;
  wheel1_ = value;
  // @@protoc_insertion_point(field_set:grSim_Robot_Command.wheel1)
}

// optional float wheel2 = 10;
inline bool grSim_Robot_Command::has_wheel2() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void grSim_Robot_Command::clear_wheel2() {
  wheel2_ = 0;
  _has_bits_[0] &= ~0x00000200u;
}
inline float grSim_Robot_Command::wheel2() const {
  // @@protoc_insertion_point(field_get:grSim_Robot_Command.wheel2)
  return wheel2_;
}
inline void grSim_Robot_Command::set_wheel2(float value) {
  _has_bits_[0] |= 0x00000200u;
  wheel2_ = value;
  // @@protoc_insertion_point(field_set:grSim_Robot_Command.wheel2)
}

// optional float wheel3 = 11;
inline bool grSim_Robot_Command::has_wheel3() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void grSim_Robot_Command::clear_wheel3() {
  wheel3_ = 0;
  _has_bits_[0] &= ~0x00000400u;
}
inline float grSim_Robot_Command::wheel3() const {
  // @@protoc_insertion_point(field_get:grSim_Robot_Command.wheel3)
  return wheel3_;
}
inline void grSim_Robot_Command::set_wheel3(float value) {
  _has_bits_[0] |= 0x00000400u;
  wheel3_ = value;
  // @@protoc_insertion_point(field_set:grSim_Robot_Command.wheel3)
}

// optional float wheel4 = 12;
inline bool grSim_Robot_Command::has_wheel4() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void grSim_Robot_Command::clear_wheel4() {
  wheel4_ = 0;
  _has_bits_[0] &= ~0x00000800u;
}
inline float grSim_Robot_Command::wheel4() const {
  // @@protoc_insertion_point(field_get:grSim_Robot_Command.wheel4)
  return wheel4_;
}
inline void grSim_Robot_Command::set_wheel4(float value) {
  _has_bits_[0] |= 0x00000800u;
  wheel4_ = value;
  // @@protoc_insertion_point(field_set:grSim_Robot_Command.wheel4)
}

// -------------------------------------------------------------------

// grSim_Commands

// required double timestamp = 1;
inline bool grSim_Commands::has_timestamp() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void grSim_Commands::clear_timestamp() {
  timestamp_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline double grSim_Commands::timestamp() const {
  // @@protoc_insertion_point(field_get:grSim_Commands.timestamp)
  return timestamp_;
}
inline void grSim_Commands::set_timestamp(double value) {
  _has_bits_[0] |= 0x00000001u;
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:grSim_Commands.timestamp)
}

// required bool isteamyellow = 2;
inline bool grSim_Commands::has_isteamyellow() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void grSim_Commands::clear_isteamyellow() {
  isteamyellow_ = false;
  _has_bits_[0] &= ~0x00000002u;
}
inline bool grSim_Commands::isteamyellow() const {
  // @@protoc_insertion_point(field_get:grSim_Commands.isteamyellow)
  return isteamyellow_;
}
inline void grSim_Commands::set_isteamyellow(bool value) {
  _has_bits_[0] |= 0x00000002u;
  isteamyellow_ = value;
  // @@protoc_insertion_point(field_set:grSim_Commands.isteamyellow)
}

// repeated .grSim_Robot_Command robot_commands = 3;
inline int grSim_Commands::robot_commands_size() const {
  return robot_commands_.size();
}
inline void grSim_Commands::clear_robot_commands() {
  robot_commands_.Clear();
}
inline ::grSim_Robot_Command* grSim_Commands::mutable_robot_commands(int index) {
  // @@protoc_insertion_point(field_mutable:grSim_Commands.robot_commands)
  return robot_commands_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::grSim_Robot_Command >*
grSim_Commands::mutable_robot_commands() {
  // @@protoc_insertion_point(field_mutable_list:grSim_Commands.robot_commands)
  return &robot_commands_;
}
inline const ::grSim_Robot_Command& grSim_Commands::robot_commands(int index) const {
  // @@protoc_insertion_point(field_get:grSim_Commands.robot_commands)
  return robot_commands_.Get(index);
}
inline ::grSim_Robot_Command* grSim_Commands::add_robot_commands() {
  // @@protoc_insertion_point(field_add:grSim_Commands.robot_commands)
  return robot_commands_.Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::grSim_Robot_Command >&
grSim_Commands::robot_commands() const {
  // @@protoc_insertion_point(field_list:grSim_Commands.robot_commands)
  return robot_commands_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_grSim_5fCommands_2eproto
